{% set name = "mkdocs-jupyter" %}
{% set version = "0.24.7" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/danielfrg/mkdocs-jupyter/archive/refs/tags/{{ version }}.tar.gz
  sha256: d6a65d505422b372ddf2ed1faf047e00778f018d3d9d2330bf72d05cf1c3e062

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.8
    - hatch >=1
  run:
    - python >=3.8
    - nbconvert >=7.2.9,<8
    - mkdocs >=1.4.0,<2
    - mkdocs-material >9.0.0
    - jupytext >1.13.8,<2
    - pygments >2.12.0
    - ipykernel <7.0.0,>6.0.0

test:
  imports:
    - mkdocs_jupyter
    - mkdocs_jupyter.tests
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/danielfrg/mkdocs-jupyter
  summary: Use Jupyter Notebooks in mkdocs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - cpcloud
    - cwognum
