{% set name = "mkdocs-jupyter" %}
{% set version = "0.22.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/mkdocs-jupyter-{{ version }}.tar.gz
  sha256: 585cc69bea4cb9faf6898131978dc9a9b225091ed4b6084f5ab65652a5e12185

build:
  number: 0
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.7
    - poetry-core >=1
    - setuptools >=57,<58
  run:
    - mkdocs >=1.2.3
    - nbconvert >=6.2
    - python >=3.7
    - jupytext >=1.13.8
    - mkdocs-material >=8.0.0
    - pygments >=2.12.0

test:
  imports:
    - mkdocs_jupyter
    - mkdocs_jupyter.tests
  commands:
    - pip check
  requires:
    - pip
    - requests  # because of `mkdocs-material` missing it for `pip check`

about:
  home: https://github.com/danielfrg/mkdocs-jupyter
  summary: Use Jupyter Notebooks in mkdocs
  license: Apache-2.0
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - hadim
    - cpcloud
